<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.ecom</groupId>
    <artifactId>ecom-microservices</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>ecom-microservices</name>
    <description>Parent aggregator for E-com microservices</description>

    <modules>
        <module>ecom</module>
        <module>ecomAPIGateWay</module>
        <module>ecomCommon</module>
        <module>ecomConfigServer</module>
        <module>ecomEureka/eureka</module>
        <module>ecomException</module>
        <module>ecomKafkaSchemaRegistry</module>
        <module>ecomOpenTelemetry</module>
        <module>ecomProductList</module>
        <module>ecomProductListUpload</module>
        <module>ecomProductListUploadAVRO</module>
        <module>ecomProductListUploadConsumer</module>
        <module>ecomPrometheus</module>
        <module>ecomSignUp</module>
        <module>KafkaConsumer</module>
        <module>kafkaProducer</module>
        <module>Product</module>
        <module>ProductReviews</module>
        <module>ecomCheckOutService</module>
        <module>security/security</module>
    </modules>

</project>
