/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ecom.productListUploadAVRO.dto;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class EcomProductListDTOAVRO extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7055780225776160972L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EcomProductListDTOAVRO\",\"namespace\":\"com.ecom.productListUploadAVRO.dto\",\"fields\":[{\"name\":\"zipFileName\",\"type\":\"string\"},{\"name\":\"uploaded\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EcomProductListDTOAVRO> ENCODER =
      new BinaryMessageEncoder<EcomProductListDTOAVRO>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EcomProductListDTOAVRO> DECODER =
      new BinaryMessageDecoder<EcomProductListDTOAVRO>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<EcomProductListDTOAVRO> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<EcomProductListDTOAVRO> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<EcomProductListDTOAVRO> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<EcomProductListDTOAVRO>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this EcomProductListDTOAVRO to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a EcomProductListDTOAVRO from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a EcomProductListDTOAVRO instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static EcomProductListDTOAVRO fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence zipFileName;
  private java.lang.CharSequence uploaded;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EcomProductListDTOAVRO() {}

  /**
   * All-args constructor.
   * @param zipFileName The new value for zipFileName
   * @param uploaded The new value for uploaded
   */
  public EcomProductListDTOAVRO(java.lang.CharSequence zipFileName, java.lang.CharSequence uploaded) {
    this.zipFileName = zipFileName;
    this.uploaded = uploaded;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return zipFileName;
    case 1: return uploaded;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: zipFileName = (java.lang.CharSequence)value$; break;
    case 1: uploaded = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'zipFileName' field.
   * @return The value of the 'zipFileName' field.
   */
  public java.lang.CharSequence getZipFileName() {
    return zipFileName;
  }


  /**
   * Sets the value of the 'zipFileName' field.
   * @param value the value to set.
   */
  public void setZipFileName(java.lang.CharSequence value) {
    this.zipFileName = value;
  }

  /**
   * Gets the value of the 'uploaded' field.
   * @return The value of the 'uploaded' field.
   */
  public java.lang.CharSequence getUploaded() {
    return uploaded;
  }


  /**
   * Sets the value of the 'uploaded' field.
   * @param value the value to set.
   */
  public void setUploaded(java.lang.CharSequence value) {
    this.uploaded = value;
  }

  /**
   * Creates a new EcomProductListDTOAVRO RecordBuilder.
   * @return A new EcomProductListDTOAVRO RecordBuilder
   */
  public static com.ecom.productListUploadAVRO.dto.EcomProductListDTOAVRO.Builder newBuilder() {
    return new com.ecom.productListUploadAVRO.dto.EcomProductListDTOAVRO.Builder();
  }

  /**
   * Creates a new EcomProductListDTOAVRO RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EcomProductListDTOAVRO RecordBuilder
   */
  public static com.ecom.productListUploadAVRO.dto.EcomProductListDTOAVRO.Builder newBuilder(com.ecom.productListUploadAVRO.dto.EcomProductListDTOAVRO.Builder other) {
    if (other == null) {
      return new com.ecom.productListUploadAVRO.dto.EcomProductListDTOAVRO.Builder();
    } else {
      return new com.ecom.productListUploadAVRO.dto.EcomProductListDTOAVRO.Builder(other);
    }
  }

  /**
   * Creates a new EcomProductListDTOAVRO RecordBuilder by copying an existing EcomProductListDTOAVRO instance.
   * @param other The existing instance to copy.
   * @return A new EcomProductListDTOAVRO RecordBuilder
   */
  public static com.ecom.productListUploadAVRO.dto.EcomProductListDTOAVRO.Builder newBuilder(com.ecom.productListUploadAVRO.dto.EcomProductListDTOAVRO other) {
    if (other == null) {
      return new com.ecom.productListUploadAVRO.dto.EcomProductListDTOAVRO.Builder();
    } else {
      return new com.ecom.productListUploadAVRO.dto.EcomProductListDTOAVRO.Builder(other);
    }
  }

  /**
   * RecordBuilder for EcomProductListDTOAVRO instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EcomProductListDTOAVRO>
    implements org.apache.avro.data.RecordBuilder<EcomProductListDTOAVRO> {

    private java.lang.CharSequence zipFileName;
    private java.lang.CharSequence uploaded;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ecom.productListUploadAVRO.dto.EcomProductListDTOAVRO.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.zipFileName)) {
        this.zipFileName = data().deepCopy(fields()[0].schema(), other.zipFileName);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.uploaded)) {
        this.uploaded = data().deepCopy(fields()[1].schema(), other.uploaded);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing EcomProductListDTOAVRO instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ecom.productListUploadAVRO.dto.EcomProductListDTOAVRO other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.zipFileName)) {
        this.zipFileName = data().deepCopy(fields()[0].schema(), other.zipFileName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.uploaded)) {
        this.uploaded = data().deepCopy(fields()[1].schema(), other.uploaded);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'zipFileName' field.
      * @return The value.
      */
    public java.lang.CharSequence getZipFileName() {
      return zipFileName;
    }


    /**
      * Sets the value of the 'zipFileName' field.
      * @param value The value of 'zipFileName'.
      * @return This builder.
      */
    public com.ecom.productListUploadAVRO.dto.EcomProductListDTOAVRO.Builder setZipFileName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.zipFileName = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'zipFileName' field has been set.
      * @return True if the 'zipFileName' field has been set, false otherwise.
      */
    public boolean hasZipFileName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'zipFileName' field.
      * @return This builder.
      */
    public com.ecom.productListUploadAVRO.dto.EcomProductListDTOAVRO.Builder clearZipFileName() {
      zipFileName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'uploaded' field.
      * @return The value.
      */
    public java.lang.CharSequence getUploaded() {
      return uploaded;
    }


    /**
      * Sets the value of the 'uploaded' field.
      * @param value The value of 'uploaded'.
      * @return This builder.
      */
    public com.ecom.productListUploadAVRO.dto.EcomProductListDTOAVRO.Builder setUploaded(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.uploaded = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'uploaded' field has been set.
      * @return True if the 'uploaded' field has been set, false otherwise.
      */
    public boolean hasUploaded() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'uploaded' field.
      * @return This builder.
      */
    public com.ecom.productListUploadAVRO.dto.EcomProductListDTOAVRO.Builder clearUploaded() {
      uploaded = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EcomProductListDTOAVRO build() {
      try {
        EcomProductListDTOAVRO record = new EcomProductListDTOAVRO();
        record.zipFileName = fieldSetFlags()[0] ? this.zipFileName : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.uploaded = fieldSetFlags()[1] ? this.uploaded : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EcomProductListDTOAVRO>
    WRITER$ = (org.apache.avro.io.DatumWriter<EcomProductListDTOAVRO>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EcomProductListDTOAVRO>
    READER$ = (org.apache.avro.io.DatumReader<EcomProductListDTOAVRO>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.zipFileName);

    out.writeString(this.uploaded);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.zipFileName = in.readString(this.zipFileName instanceof Utf8 ? (Utf8)this.zipFileName : null);

      this.uploaded = in.readString(this.uploaded instanceof Utf8 ? (Utf8)this.uploaded : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.zipFileName = in.readString(this.zipFileName instanceof Utf8 ? (Utf8)this.zipFileName : null);
          break;

        case 1:
          this.uploaded = in.readString(this.uploaded instanceof Utf8 ? (Utf8)this.uploaded : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










