# Eureka server
server.port=5000
spring.application.name=ecom-eureka-server

eureka.instance.hostname=localhost
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.serviceUrl.defaultZone=http://localhost:5000/eureka
eureka.dashboard.path=/dashboard

# Actuator / monitoring
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
