spring.application.name=ecomAccounts
server.port=8086

spring.config.import=optional:configserver:http://localhost:8888
spring.profiles.active=dev

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
