app:
  datasource:
    mysql:
      url: jdbc:mysql://localhost:3310/ecomProdDB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      username: ecomUser
      password: root123
      driver-class-name: com.mysql.cj.jdbc.Driver
    vector:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: root123
      driver-class-name: org.postgresql.Driver
  embedding:
    enabled: true
    active-profile: openai
    profiles:
      openai:
        provider: openai
        model: text-embedding-3-small
        base-url: https://api.openai.com/v1
        api-key: ${OPENAI_API_KEY:}
        dimension: 1536
      qwen:
        provider: ollama
        model: qwen3-embedding:0.6b
        base-url: http://localhost:11434
        api-key:
        dimension: 1024

spring:
  sql:
    init:
      mode: never
